ebook_metadata:
  title: ༄༅། སྔ་འགྱུར་བཀའ་གཏེར་ཤིང་རྟའི་ལམ་སྲོལ་ཆོས་ཀྱི་རྒྱལ་པོ་སྨིན་གླིང་པའི་བསྟན་པ་རྒྱས་པའི་སྨོན་ལམ་རྡོ་རྗེའི་གསུང་གི་འགྲེལ་པ་དགེ་མཚན་ལྷ་ཡི་རྔ་ཆེན་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  sku: SHE-DKR-15
  layers:
  - book_title
  - author
web_metadata:
  title:
    en: A Magnificent Divine Drum:A Commentary on the “Vajra Speech,” a Prayer for
      the Spread of the Teaching According to the Mindroling Tradition
    bo: སྔ་འགྱུར་བཀའ་གཏེར་ཤིང་རྟའི་ལམ་སྲོལ་ཆོས་ཀྱི་རྒྱལ་པོ་སྨིན་གླིང་པའི་བསྟན་པ་རྒྱས་པའི་སྨོན་ལམ་རྡོ་རྗེའི་གསུང་གི་འགྲེལ་པ་དགེ་མཚན་ལྷ་ཡི་རྔ་ཆེན་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 15
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༡༥
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-15
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-15.epub
  description:
    en: ''
    bo: ''
